<?php define('undefined', 'undefined');require __DIR__.'/../driver.inc.php';
$html = file_get_contents(__DIR__."/../nodes/CharacterData-appendData.html");
$document = DOM\HTMLDocument::createFromString($html);
;
function testNode($create, $type) {global $document;
  test(function() use ($create, $type) {global $document;
    $node = $create();
    assert_equals($node->data, "test");
;
    $node->appendData("bar");
    assert_equals($node->data, "testbar");
  }, $type . "->appendData('bar')");
;
  test(function() use ($create, $type) {global $document;
    $node = $create();
    assert_equals($node->data, "test");
;
    $node->appendData("");
    assert_equals($node->data, "test");
  }, $type . "->appendData('')");
;
  test(function() use ($create, $type) {global $document;
    $node = $create();
    assert_equals($node->data, "test");
    $node->appendData(", append more 資料，測試資料");
    assert_equals($node->data, "test, append more 資料，測試資料");
    assert_equals($node->length, 25);
  }, $type . "->appendData(non-ASCII)");
;
  /*test(function() use ($create, $type) {global $document;
    $node = $create();
    assert_equals($node->data, "test");
;
    $node->appendData(null);
    assert_equals($node->data, "testnull");
  }, $type . "->appendData(null)");*/
;
  test(function() use ($create, $type) {global $document;
    $node = $create();
    assert_equals($node->data, "test");
;
    $node->appendData(undefined);
    assert_equals($node->data, "testundefined");
  }, $type . "->appendData(undefined)");
;
  test(function() use ($create, $type) {global $document;
    $node = $create();
    assert_equals($node->data, "test");
;
  $node->appendData(""/*, "bar"*/);
    assert_equals($node->data, "test");
  }, $type . "->appendData('', 'bar')");
;
  test(function() use ($create, $type) {global $document;
    $node = $create();
    assert_equals($node->data, "test");
;
    //assert_throws_js(TypeError, function() { $node->appendData(); });
    assert_equals($node->data, "test");
  }, $type . "->appendData()");
};
;
testNode(function() {global $document; return $document->createTextNode("test"); }, "Text");
testNode(function() {global $document; return $document->createComment("test"); }, "Comment");
;