<?php define('undefined', 'undefined');require __DIR__.'/../driver.inc.php';
$html = file_get_contents(__DIR__."/../nodes/ChildNode-after.html");
$document = DOM\HTMLDocument::createFromString($html);
;
;
function test_after($child, $nodeName, $innerHTML) {global $document;
;
    test(function() use ($child, $nodeName, $innerHTML) {global $document;
        $parent = $document->createElement('div');
        $parent->appendChild($child);
        $child->after();
        assert_equals(innerHTML($parent), $innerHTML);
    }, $nodeName . '->after() without any argument->');
;
    test(function() use ($child, $nodeName, $innerHTML) {global $document;
        $parent = $document->createElement('div');
        $parent->appendChild($child);
        $child->after(null);
        $expected = $innerHTML . 'null';
        assert_equals(innerHTML($parent), $expected);
    }, $nodeName . '->after() with null as an argument->');
;
    test(function() use ($child, $nodeName, $innerHTML) {global $document;
        $parent = $document->createElement('div');
        $parent->appendChild($child);
        $child->after(undefined);
        $expected = $innerHTML . 'undefined';
        assert_equals(innerHTML($parent), $expected);
    }, $nodeName . '->after() with undefined as an argument->');
;
    test(function() use ($child, $nodeName, $innerHTML) {global $document;
        $parent = $document->createElement('div');
        $parent->appendChild($child);
        $child->after('');
        assert_equals($parent->lastChild->data, '');
    }, $nodeName . '->after() with the empty string as an argument->');
;
    test(function() use ($child, $nodeName, $innerHTML) {global $document;
        $parent = $document->createElement('div');
        $parent->appendChild($child);
        $child->after('text');
        $expected = $innerHTML . 'text';
        assert_equals(innerHTML($parent), $expected);
    }, $nodeName . '->after() with only text as an argument->');
;
    test(function() use ($child, $nodeName, $innerHTML) {global $document;
        $parent = $document->createElement('div');
        $x = $document->createElement('x');
        $parent->appendChild($child);
        $child->after($x);
        $expected = $innerHTML . '<x></x>';
        assert_equals(innerHTML($parent), $expected);
    }, $nodeName . '->after() with only one element as an argument->');
;
    test(function() use ($child, $nodeName, $innerHTML) {global $document;
        $parent = $document->createElement('div');
        $x = $document->createElement('x');
        $parent->appendChild($child);
        $child->after($x, 'text');
        $expected = $innerHTML . '<x></x>text';
        assert_equals(innerHTML($parent), $expected);
    }, $nodeName . '->after() with one element and text as arguments->');
;
    test(function() use ($child, $nodeName, $innerHTML) {global $document;
        $parent = $document->createElement('div');
        $parent->appendChild($child);
        $child->after('text', $child);
        $expected = 'text' . $innerHTML;
        assert_equals(innerHTML($parent), $expected);
    }, $nodeName . '->after() with context object itself as the argument->');
;
    test(function() use ($child, $nodeName, $innerHTML) {global $document;
        $parent = $document->createElement('div');
        $x = $document->createElement('x');
        $parent->appendChild($x);
        $parent->appendChild($child);
        $child->after($child, $x);
        $expected = $innerHTML . '<x></x>';
        assert_equals(innerHTML($parent), $expected);
    }, $nodeName . '->after() with context object itself and node as the arguments, switching positions->');
;
    test(function() use ($child, $nodeName, $innerHTML) {global $document;
        $parent = $document->createElement('div');
        $x = $document->createElement('x');
        $y = $document->createElement('y');
        $z = $document->createElement('z');
        $parent->appendChild($y);
        $parent->appendChild($child);
        $parent->appendChild($x);
        $child->after($x, $y, $z);
        $expected = $innerHTML . '<x></x><y></y><z></z>';
        assert_equals(innerHTML($parent), $expected);
    }, $nodeName . '->after() with all siblings of child as arguments->');
;
    test(function() use ($child, $nodeName, $innerHTML) {global $document;
        $parent = $document->createElement('div');
        $x = $document->createElement('x');
        $y = $document->createElement('y');
        $z = $document->createElement('z');
        $parent->appendChild($child);
        $parent->appendChild($x);
        $parent->appendChild($y);
        $parent->appendChild($z);
        $child->after($x, $y);
        $expected = $innerHTML . '<x></x><y></y><z></z>';
        assert_equals(innerHTML($parent), $expected);
    }, $nodeName . '->before() with some siblings of child as arguments; no changes in tree; viable sibling is first $child->');
;
    test(function() use ($child, $nodeName, $innerHTML) {global $document;
        $parent = $document->createElement('div');
        $v = $document->createElement('v');
        $x = $document->createElement('x');
        $y = $document->createElement('y');
        $z = $document->createElement('z');
        $parent->appendChild($child);
        $parent->appendChild($v);
        $parent->appendChild($x);
        $parent->appendChild($y);
        $parent->appendChild($z);
        $child->after($v, $x);
        $expected = $innerHTML . '<v></v><x></x><y></y><z></z>';
        assert_equals(innerHTML($parent), $expected);
    }, $nodeName . '->after() with some siblings of child as arguments; no changes in tree->');
;
    test(function() use ($child, $nodeName, $innerHTML) {global $document;
        $parent = $document->createElement('div');
        $x = $document->createElement('x');
        $y = $document->createElement('y');
        $parent->appendChild($child);
        $parent->appendChild($x);
        $parent->appendChild($y);
        $child->after($y, $x);
        $expected = $innerHTML . '<y></y><x></x>';
        assert_equals(innerHTML($parent), $expected);
    }, $nodeName . '->after() when pre-insert behaves like append->');
;
    test(function() use ($child, $nodeName, $innerHTML) {global $document;
        $parent = $document->createElement('div');
        $x = $document->createElement('x');
        $y = $document->createElement('y');
        $parent->appendChild($child);
        $parent->appendChild($x);
        $parent->appendChild($document->createTextNode('1'));
        $parent->appendChild($y);
        $child->after($x, '2');
        $expected = $innerHTML . '<x></x>21<y></y>';
        assert_equals(innerHTML($parent), $expected);
    }, $nodeName . '->after() with one sibling of child and text as arguments->');
;
    test(function() use ($child, $nodeName, $innerHTML) {global $document;
        $x = $document->createElement('x');
        $y = $document->createElement('y');
        $x->after($y);
        assert_equals($x->nextSibling, null);
    }, $nodeName . '->after() on a child without any $parent->');
};
;
test_after($document->createComment('test'), 'Comment', '<!--test-->');
test_after($document->createElement('test'), 'Element', '<test></test>');
test_after($document->createTextNode('test'), 'Text', 'test');
;
;