<?php define('undefined', 'undefined');require __DIR__.'/../driver.inc.php';
$content = file_get_contents(__DIR__."/../nodes/Document-getElementsByClassName.html");
$document = Dom\HTMLDocument::createFromString($content);
;
test(function()  {global $document;
  $a = $document->createElement("a");
  $b = $document->createElement("b");
  $a->className = "foo";
  $document->body->appendChild($a);
;
  $l = $document->getElementsByClassName("foo");
  assert_true($l instanceof Dom\HTMLCollection);
  assert_equals($l->length, 1);
;
  $b->className = "foo";
  $document->body->appendChild($b);
  assert_equals($l->length, 2);
;
  $document->body->removeChild($b);
  assert_equals($l->length, 1);
}, "getElementsByClassName() should be a live collection");
;