<?php define('undefined', 'undefined');require __DIR__.'/../driver.inc.php';
$html = file_get_contents(__DIR__."/../nodes/Element-hasAttribute.html");
$document = DOM\HTMLDocument::createFromString($html);
;
"use strict";
;
test(function(){global $document;
;
  $el = $document->createElement("p");
  $el->setAttributeNS("foo", "x", "first");
;
  assert_true($el->hasAttribute("x"));
;
}, "hasAttribute should check for attribute presence, irrespective of namespace");
;
test(function(){global $document;
;
  $el = $document->getElementById("t");
;
  assert_true($el->hasAttribute("data-e2"));
  assert_true($el->hasAttribute("data-E2"));
  assert_true($el->hasAttribute("data-f2"));
  assert_true($el->hasAttribute("data-F2"));
;
}, "hasAttribute should work with all attribute casings");
;