<?php define('undefined', 'undefined');require __DIR__.'/../driver.inc.php';
$html = file_get_contents(__DIR__."/../nodes/getElementsByClassName-04.htm");
$document = DOM\HTMLDocument::createFromString($html);
;
   test(function()  {global $document;
          $collection = $document->getElementsByClassName("a");
          $document->body->className .= "\tb";
          assert_array_equals($collection, [$document->documentElement, $document->body]);
        });
  ;