<?php define('undefined', 'undefined');require __DIR__.'/../driver.inc.php';
$html = file_get_contents(__DIR__."/../nodes/Node-cloneNode-svg.html");
$document = DOM\HTMLDocument::createFromString($html);
;
"use strict";
;
$svg = $document->getElementsByTagName("svg")[0];
$clone = $svg->cloneNode(true);
;
test(function(){global $document;global $clone;
;
  assert_equals($clone->namespaceURI, "http://www.w3.org/2000/svg");
  assert_equals($clone->prefix, null);
  assert_equals($clone->localName, "svg");
  assert_equals($clone->tagName, "svg");
;
}, "cloned <svg> should have the right properties");
;
test(function(){global $document;global $clone;
;
  $attr = $clone->attributes[0];
;
  assert_equals($attr->namespaceURI, "http://www.w3.org/2000/xmlns/");
  assert_equals($attr->prefix, "xmlns");
  assert_equals($attr->localName, "xlink");
  assert_equals($attr->name, "xmlns:xlink");
  assert_equals($attr->value, "http://www.w3.org/1999/xlink");
;
}, "cloned <svg>'s xmlns:xlink attribute should have the right properties");
;
test(function(){global $document;global $clone;
;
  $use = $clone->firstElementChild;
  assert_equals($use->namespaceURI, "http://www.w3.org/2000/svg");
  assert_equals($use->prefix, null);
  assert_equals($use->localName, "use");
  assert_equals($use->tagName, "use");
;
}, "cloned <use> should have the right properties");
;
test(function(){global $document;global $clone;
;
  $use = $clone->firstElementChild;
  $attr = $use->attributes[0];
;
  assert_equals($attr->namespaceURI, "http://www.w3.org/1999/xlink");
  assert_equals($attr->prefix, "xlink");
  assert_equals($attr->localName, "href");
  assert_equals($attr->name, "xlink:href");
  assert_equals($attr->value, "#test");
;
}, "cloned <use>'s xlink:href attribute should have the right properties");
;
;