<?php define('undefined', 'undefined');require __DIR__.'/../driver.inc.php';
$html = file_get_contents(__DIR__."/../nodes/ParentNode-append.html");
$document = DOM\HTMLDocument::createFromString($html);
;
//preInsertionValidateHierarchy("append");
;
function test_append($node, $nodeName) {global $document;
    test(function() use ($node, $nodeName) {global $document;
        $parent = $node->cloneNode();
        $parent->append();
        assert_array_equals($parent->childNodes, []);
    }, $nodeName . '->append() without any argument, on a parent having no $child->');
;
    test(function() use ($node, $nodeName) {global $document;
        $parent = $node->cloneNode();
        $parent->append(null);
        assert_equals($parent->childNodes[0]->textContent, 'null');
    }, $nodeName . '->append() with null as an argument, on a parent having no $child->');
;
    test(function() use ($node, $nodeName) {global $document;
        $parent = $node->cloneNode();
        $parent->append(undefined);
        assert_equals($parent->childNodes[0]->textContent, 'undefined');
    }, $nodeName . '->append() with undefined as an argument, on a parent having no $child->');
;
    test(function() use ($node, $nodeName) {global $document;
        $parent = $node->cloneNode();
        $parent->append('text');
        assert_equals($parent->childNodes[0]->textContent, 'text');
    }, $nodeName . '->append() with only text as an argument, on a parent having no $child->');
;
    test(function() use ($node, $nodeName) {global $document;
        $parent = $node->cloneNode();
        $x = $document->createElement('x');
        $parent->append($x);
        assert_array_equals($parent->childNodes, [$x]);
    }, $nodeName . '->append() with only one element as an argument, on a parent having no $child->');
;
    test(function() use ($node, $nodeName) {global $document;
        $parent = $node->cloneNode();
        $child = $document->createElement('test');
        $parent->appendChild($child);
        $parent->append(null);
        assert_equals($parent->childNodes[0], $child);
        assert_equals($parent->childNodes[1]->textContent, 'null');
    }, $nodeName . '->append() with null as an argument, on a parent having a $child->');
;
    test(function() use ($node, $nodeName) {global $document;
        $parent = $node->cloneNode();
        $x = $document->createElement('x');
        $child = $document->createElement('test');
        $parent->appendChild($child);
        $parent->append($x, 'text');
        assert_equals($parent->childNodes[0], $child);
        assert_equals($parent->childNodes[1], $x);
        assert_equals($parent->childNodes[2]->textContent, 'text');
    }, $nodeName . '->append() with one element and text as argument, on a parent having a $child->');
};
;
test_append($document->createElement('div'), 'Element');
test_append($document->createDocumentFragment(), 'DocumentFragment');
;