<?php define('undefined', 'undefined');require __DIR__.'/../driver.inc.php';
$html = file_get_contents(__DIR__."/../nodes/prepend-on-Document.html");
$document = DOM\HTMLDocument::createFromString($html);
;
;
function test_prepend_on_Document() {global $document;
;
    $node = DOM\XMLDocument::createEmpty();
    test(function()  use($node){global $document;
        $parent = $node->cloneNode();
        $parent->prepend();
        assert_array_equals($parent->childNodes, []);
    }, 'Document->prepend() without any argument, $on a Document having no child->');
;
    test(function() use($node) {global $document;
        $parent = $node->cloneNode();
        $x = $document->createElement('x');
        $parent->prepend($x);
        assert_array_equals($parent->childNodes, [$x]);
    }, 'Document->prepend() with only one element as an argument, $on a Document having no child->');
;
    test(function()  use($node){global $document;
        $parent = $node->cloneNode();
        $x = $document->createElement('x');
        $y = $document->createElement('y');
        $parent->appendChild($x);
        assert_throws_dom('HIERARCHY_REQUEST_ERR', function() use($parent,$y) { $parent->prepend($y); });
        assert_array_equals($parent->childNodes, [$x]);
    }, 'Document->append() with only one element as an argument, $on a Document having one child->');
;
    test(function() use($node) {global $document;
        $parent = $node->cloneNode();
        assert_throws_dom('HIERARCHY_REQUEST_ERR', function() use($parent) { $parent->prepend('text'); });
        assert_array_equals($parent->childNodes, []);
    }, 'Document->prepend() with text as an argument, $on a Document having no child->');
;
    test(function() use($node) {global $document;
        $parent = $node->cloneNode();
        $x = $document->createElement('x');
        $y = $document->createElement('y');
        assert_throws_dom('HIERARCHY_REQUEST_ERR', function() use($parent,$x,$y) { $parent->prepend($x, $y); });
        assert_array_equals($parent->childNodes, []);
    }, 'Document->prepend() with two elements as the argument, $on a Document having no child->');
;
};
;
test_prepend_on_Document();
;
;